name: Stratocraft
version: 10.0
main: me.mami.stratocraft.Main
api-version: 1.20
authors: [Mami]
depend: [WorldEdit]
commands:
  klan:
    description: Klan yonetim komutlari.
    usage: /klan <kur|kristal|davet|ayril>
  kontrat:
    description: Kontrat panosu islemleri.
    usage: /kontrat <list|olustur|teslim>